FROM ubuntu:20.04

RUN apt-get update &&     apt-get install -y openssh-server sudo &&     mkdir /var/run/sshd

RUN useradd -m ansible && echo "ansible:ansible" | chpasswd &&     usermod -aG sudo ansible

RUN echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config &&     sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]